export default {
  SAGA_WORLD: 'SAGA_WORLD',
  LOGIN: 'LOGIN',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  CLEAR_API_VALIDATION_ERR: 'CLEAR_API_VALIDATION_ERR',
  CLEAR_ALL_API_VALIDATION_ERRS: 'CLEAR_ALL_API_VALIDATION_ERRS',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN',
  SOCIAL_LOGIN_REDIRECT: 'SOCIAL_LOGIN_REDIRECT'
};
