export default {
  SAGA_WORLD: 'SAGA_WORLD',
  LOGIN: 'LOGIN',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  CLEAR_API_VALIDATION_ERR: 'CLEAR_API_VALIDATION_ERR',
  CLEAR_ALL_API_VALIDATION_ERRS: 'CLEAR_ALL_API_VALIDATION_ERRS',
  LOGGED_IN_USER_PROFILE: 'LOGGED_IN_USER_PROFILE',
  LOGOUT: 'LOGOUT',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN',
  SOCIAL_LOGIN_REDIRECT: 'SOCIAL_LOGIN_REDIRECT',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  LOAD_ARTICLE: 'LOAD_ARTICLE',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE'
};
